[repository]
name = "hyprland-plugins"
authors = ["Vaxry"]

[borders-plus-plus]
description = "A plugin to add more borders to windows."
authors = ["Vaxry"]
output = "borders-plus-plus/borders-plus-plus.so"
build = [
    "make -C borders-plus-plus all",
]

[csgo-vulkan-fix]
description = "A plugin to fix incorrect mouse offsets on csgo in Vulkan"
authors = ["Vaxry"]
output = "csgo-vulkan-fix/csgo-vulkan-fix.so"
build = [
    "make -C csgo-vulkan-fix all",
]

[hyprbars]
description = "A plugin to add title bars to windows"
authors = ["Vaxry"]
output = "hyprbars/hyprbars.so"
build = [
    "make -C hyprbars all",
]

[hyprfocus]
description = "Flashfocus for Hyprland"
authors = ["Vaxry"]
output = "hyprfocus/hyprfocus.so"
build = [
    "make -C hyprfocus all",
]
since_hyprland = 6066
